artifact_uri: /Users/emre/Desktop/Position-12450-Technical-Interview-Exercise-Yesilyurt/mlflow/181247617744572816/29c0ddf0846c4ba6a4ad28bcb4a87ac1/artifacts
end_time: 1687870008722
entry_point_name: ''
experiment_id: '181247617744572816'
lifecycle_stage: active
run_id: 29c0ddf0846c4ba6a4ad28bcb4a87ac1
run_name: traveling-tern-18
run_uuid: 29c0ddf0846c4ba6a4ad28bcb4a87ac1
source_name: ''
source_type: 4
source_version: ''
start_time: 1687870008317
status: 3
tags: []
user_id: emre
