artifact_uri: /Users/emre/Desktop/Position-12450-Technical-Interview-Exercise-Yesilyurt/mlflow/181247617744572816/4fd2ec685c8945b3ac1eebbd29bcd1d3/artifacts
end_time: 1687809378284
entry_point_name: ''
experiment_id: '181247617744572816'
lifecycle_stage: active
run_id: 4fd2ec685c8945b3ac1eebbd29bcd1d3
run_name: bemused-newt-941
run_uuid: 4fd2ec685c8945b3ac1eebbd29bcd1d3
source_name: ''
source_type: 4
source_version: ''
start_time: 1687809378134
status: 3
tags: []
user_id: emre
